apiVersion: v1
kind: Namespace
metadata:
  name: ${NAMESPACE}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-backend
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: golang-backend
    spec:
      containers:
      - name: golang-backend
        image: dhanifajar15/golang-backend:${IMAGE_TAG}
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
        resources:
          requests:
            memory: "250Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: golang-backend
  namespace: ${NAMESPACE}
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: golang-backend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: golang-backend-ingress
  namespace: ${NAMESPACE}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host:  ${INGRESS_HOST}
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: golang-backend
            port:
              number: 80
