name: Deploy
on:
  workflow_call:
    inputs:
      INGRESS_HOST:
        type: string
        required: true
      NAMESPACE:
        type: string
        required: true
      ENVIRONMENT:
        type: string
        required: true
    secrets:
      PROJECT_ID:
        required: true
      APPLICATION_CREDENTIALS:
        required: true
      CLUSTER_NAME:
        required: true
      ZONE_NAME:
        required: true
jobs:
  #---------------------------------------------------------------------------------------------------------------------
  # Deploy
  #---------------------------------------------------------------------------------------------------------------------
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    # Set Docker Tag
    - name: Get Docker Tag
      id: tags
      run: |
        echo ::set-output name=sha_short::$(git rev-parse --short=7 ${{ github.sha }})
    # Setup application manifest
    - uses: danielr1996/envsubst-action@1.0.0
      env:
        IMAGE_TAG: ${{ inputs.ENVIRONMENT }}-sha-${{ steps.tags.outputs.sha_short }}
        INGRESS_HOST: ${{ inputs.INGRESS_HOST }}
        NAMESPACE: ${{ inputs.NAMESPACE }}
      with:
        input: deployment/deployment.yaml
        output: manifest.yaml
    - name: kubectl - Google Cloud GKE cluster.
      uses: ameydev/gke-kubectl-action@master
      env:
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        APPLICATION_CREDENTIALS: ${{ secrets.APPLICATION_CREDENTIALS }}
        CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
        ZONE_NAME: ${{ secrets.ZONE_NAME }}
      with:
        args: apply -f manifest.yaml
