name: Development
on:
  workflow_dispatch:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - staging
jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
  docker:
    name: Containerization
    uses: ./.github/workflows/docker.yml
    needs:
    - test
    with:
      ENVIRONMENT: dev
    secrets:
      USERNAME: ${{ secrets.DOCKER_USERNAME }}
      PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  deploy:
    name: Deployment
    uses: ./.github/workflows/deploy.yml
    needs:
    - docker
    with:
      INGRESS_HOST: dev-${{github.sha}}.34.142.207.149.nip.io
      NAMESPACE: development
      ENVIRONMENT: dev
    secrets:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
      ZONE_NAME: ${{ secrets.ZONE_NAME }}

